export default [
  { kana: 'いる', translation: 'be; exist (animate)' },
  { kana: 'ある', translation: 'be; exist (inanimate)' },
  { kana: '持つ', furigana: 'もつ', translation: 'have; hold; own' },
  { kana: '行く', furigana: 'いく', translation: 'go' },
  { kana: '買う', furigana: 'かう', translation: 'buy' },
  { kana: '食べる', furigana: 'たべる', translation: 'eat' },
  { kana: '飲む', furigana: 'のむ', translation: 'drink' },
  { kana: '見る', furigana: 'みる', translation: 'see; look; watch' },
  { kana: '聞く', furigana: 'きく', translation: 'hear; listen; ask' },
  { kana: '分かる', furigana: 'わかる', translation: 'know; understand' },
  {
    kana: '会う',
    furigana: 'あう',
    translation: 'meet',
    examples: [
      { kana: '友達に会いに行きます', translation: "I'm going to meet a friend." },
      { kana: '昨日田中さんに会いました', translation: 'I met Tanaka yesterday.' },
      { kana: '7時にホテルの外で会いましょう', translation: "Let's meet outside the hotel at 7." },
    ],
  },
  { kana: '歩く', furigana: 'あるく', translation: 'walk' },
  { kana: '言う', furigana: 'いう', translation: 'say; tell' },
  { kana: '売る', furigana: 'うる', translation: 'sell' },
  { kana: '置く', furigana: 'おく', translation: 'put; place' },
  { kana: '乗る', furigana: 'のる', translation: 'board; ride' },
  { kana: '降りる', furigana: 'おりる', translation: 'get off; descend; dismount' },
  { kana: '着る', furigana: 'きる', translation: 'put on; wear' },
  { kana: '住む', furigana: 'すむ', translation: 'live; reside' },
  { kana: '勤める', furigana: 'つとめる', translation: 'work for; be employed by' },
  { kana: '寝る', furigana: 'ねる', translation: 'go to bed; sleep' },
  { kana: '休む', furigana: 'やすむ', translation: 'rest; sleep' },
  { kana: '払う', furigana: 'はらう', translation: 'pay' },
  { kana: '話す', furigana: 'はなす', translation: 'talk; speak; tell' },
  { kana: '待つ', furigana: 'まつ', translation: 'wait' },
]
